name: 'Update Issue Sprint'
description: 'Adds and removes sprints from issues.'
inputs:
  repo-token:
    description: 'The GitHub token'
    required: false
    default: ${{ github.token }}
  issue-column:
    description: 'The column where the issue resides'
    required: true
branding:
  icon: zap-off
  color: orange
runs:
  using: 'node12'
  main: 'sprint.js'
